import { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { request } from 'undici'
import styles from '../styles/Home.module.css'
const Home: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ content }) =>  {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {content}
        </h1>

      </main>
    </div>
  )
}

export default Home;

const getContent = async () => {
  const { body } = await request('http://localhost:3001/content');
  const { content } =  await body.json();
  return content as string;
}


export const getServerSideProps = async () => {
  // todo - fetching
  const content = await getContent();

  return {
    props: {
      content,
    }
  }
}
