name: Build and deploy main branch
on:
  push:
    paths-ignore:
      - blog/**
      - test-subjects/**
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/install-dependencies
      - name: Lint
        run: yarn lint
  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    if: "!contains(github.event.head_commit.message, 'chore: publish')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install dependencies
        uses: ./.github/install-dependencies
      - name: Configure Git
        run: |
          git --version
          git config --global user.email alex@gait.dev
          git config --global user.name Alex Traher
          git remote rm origin
          git remote add origin "https://alextraher:$GITHUB_TOKEN@github.com/AlexTraher/gait-toolkit.git"
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Build changed
        run: yarn build
      - name: Authenticate with NPM
        run: |
          yarn logout
          echo "@gait-tools:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Version and publish
        run: |
          yarn run version
          yarn run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ github.token }}